development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: my_blog_rails_development
  pool: 5
  username: cponcax
  password: bat86

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: my_blog_rails_test
  pool: 5
  username: cponcax
  password: bat86

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: my_blog_rails_production
  pool: 5
  username: cponcax
  password: bat86

